//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIGRATING_RECRUITMENT.NEW_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDITIONAL_INFO
    {
        public string FILENO { get; set; }
        public Nullable<System.DateTime> DINC { get; set; }
        public Nullable<System.DateTime> LDINC { get; set; }
        public string REM { get; set; }
        public string PFLAG { get; set; }
        public string PCODE { get; set; }
        public Nullable<double> MONTH { get; set; }
        public Nullable<double> RATE { get; set; }
        public string PROVISIONAL { get; set; }
        public string MEDICAL { get; set; }
    }
}
