//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIGRATING_RECRUITMENT.NEW_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_DETAIL
    {
        public string FILENO { get; set; }
        public string STAT { get; set; }
        public string DEPT { get; set; }
        public string DESIG { get; set; }
        public Nullable<System.DateTime> DTAP { get; set; }
        public Nullable<System.DateTime> EXTN { get; set; }
        public Nullable<System.DateTime> DRLF { get; set; }
        public string OLD_FILENO { get; set; }
        public string DESIGN { get; set; }
        public string DEPARTMENT { get; set; }
        public Nullable<System.DateTime> EXTN_DATE { get; set; }
    }
}
