//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIGRATING_RECRUITMENT.NEW_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class META
    {
        public string FILENO { get; set; }
        public Nullable<System.DateTime> DT_INP { get; set; }
        public Nullable<System.DateTime> DT_CHG { get; set; }
    }
}
