//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIGRATING_RECRUITMENT.NEW_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_PHD
    {
        public string FILENO { get; set; }
        public string COURSE { get; set; }
        public string SEMESTER { get; set; }
        public string YR { get; set; }
    }
}
