//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIGRATING_RECRUITMENT.NEW_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RECRUITMENTEntities : DbContext
    {
        public RECRUITMENTEntities()
            : base("name=RECRUITMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDITIONAL_INFO> ADDITIONAL_INFO { get; set; }
        public virtual DbSet<META> META { get; set; }
        public virtual DbSet<MS_PHD> MS_PHD { get; set; }
        public virtual DbSet<PROJECT_INFO> PROJECT_INFO { get; set; }
        public virtual DbSet<PAY_DETAIL> PAY_DETAIL { get; set; }
        public virtual DbSet<PERSONAL_INFO> PERSONAL_INFO { get; set; }
        public virtual DbSet<EMP_DETAIL> EMP_DETAIL { get; set; }
        public virtual DbSet<RECRUIT_TYPE> RECRUIT_TYPE { get; set; }
    }
}
