//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIGRATING_RECRUITMENT.NEW_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAY_DETAIL
    {
        public string FILENO { get; set; }
        public Nullable<double> BAISC { get; set; }
        public Nullable<double> INCR { get; set; }
        public Nullable<double> HRA { get; set; }
        public string PAYBILL_ID { get; set; }
        public string PAYBILL_NO { get; set; }
    }
}
