//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIGRATING_RECRUITMENT.NEW_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL_INFO
    {
        public string FILENO { get; set; }
        public string NAME { get; set; }
        public string SCSTOS { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string FATHER { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string ADDRESS4 { get; set; }
        public string CITY { get; set; }
        public string SEX { get; set; }
        public string BLDGRP { get; set; }
        public string RH { get; set; }
        public string PHONE { get; set; }
        public string R_ADDR1 { get; set; }
        public string R_ADDR2 { get; set; }
        public string R_CITY { get; set; }
        public string R_PIN { get; set; }
        public string R_PHONE { get; set; }
        public string R_ADDR3 { get; set; }
        public string R_ADDR4 { get; set; }
        public string EMAIL_ID { get; set; }
        public string PENSIONER { get; set; }
        public string QUALIFICATION { get; set; }
    }
}
