//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIGRATING_RECRUITMENT.NEW_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_INFO
    {
        public string FILENO { get; set; }
        public string TITLE { get; set; }
        public string PROJECTNO { get; set; }
        public string PTYPE { get; set; }
        public string SPON { get; set; }
        public string COOR { get; set; }
        public string COO { get; set; }
    }
}
