//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIGRATING_RECRUITMENT.OLD_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWREG
    {
        public string EMPCODE { get; set; }
        public string STAT { get; set; }
        public string TITLE { get; set; }
        public string PROJECTNO { get; set; }
        public string PTYPE { get; set; }
        public string NAME { get; set; }
        public string DEPT { get; set; }
        public string SPON { get; set; }
        public string DESIG { get; set; }
        public Nullable<System.DateTime> DTAP { get; set; }
        public Nullable<System.DateTime> EXTN { get; set; }
        public Nullable<System.DateTime> DRLF { get; set; }
        public Nullable<double> BASIC { get; set; }
        public Nullable<double> INCR { get; set; }
        public Nullable<System.DateTime> DINC { get; set; }
        public Nullable<System.DateTime> LDINC { get; set; }
        public string COOR { get; set; }
        public string REM { get; set; }
        public string SCSTOS { get; set; }
        public string FILENO { get; set; }
        public string OLD_FILENO { get; set; }
        public string DESIGN { get; set; }
        public string COO { get; set; }
        public string PFLAG { get; set; }
        public Nullable<double> HRA { get; set; }
        public Nullable<System.DateTime> DT_INP { get; set; }
        public Nullable<System.DateTime> DT_CHG { get; set; }
        public string PCODE { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string DEPARTMENT { get; set; }
        public string FATHER { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string ADDRESS4 { get; set; }
        public string CITY { get; set; }
        public Nullable<double> MONTH { get; set; }
        public Nullable<double> RATE { get; set; }
        public string SEX { get; set; }
        public string BLDGRP { get; set; }
        public string RH { get; set; }
        public string PHONE { get; set; }
        public string R_ADDR1 { get; set; }
        public string R_ADDR2 { get; set; }
        public string R_CITY { get; set; }
        public string R_PIN { get; set; }
        public string R_PHONE { get; set; }
        public string R_ADDR3 { get; set; }
        public string R_ADDR4 { get; set; }
        public string COURSE { get; set; }
        public string SEMESTER { get; set; }
        public string YR { get; set; }
        public string PROVISIONAL { get; set; }
        public string MEDICAL { get; set; }
        public Nullable<System.DateTime> extn_date { get; set; }
        public string paybill_id { get; set; }
        public string paybill_no { get; set; }
        public string email_id { get; set; }
        public string Pensioner { get; set; }
        public string Qualification { get; set; }
    }
}
